add "post" verb

diff --git a/git-rest b/git-rest
--- a/git-rest
+++ b/git-rest
@@ -26,6 +26,14 @@ case "$1" in
         fi
         git tag -d $2
         ;;
+    post)
+        if [ -z $2 ]; then
+            echo "Missing object name argument!"
+            exit 111
+        fi
+        hash=`git hash-object -w --stdin`
+        git tag -d $2 > /dev/null && git tag $2 $hash
+        ;;
     *)
         echo "usage: git rest [put|get|delete] tagname"
         ;;
